/**
 * @Author HuangChuan
 * @Create in 2022/03/02 15:56
 */
public enum Keyword {
	CLASS, METHOD, INT, FUNCTION, BOOLEAN, CONSTRUCTOR, CHAR, VOID, VAR, STATIC, FIELD, LET, DO,
	IF, ELSE, WHILE, RETURN, TRUE, FALSE, NULL, THIS
}
